[project]
name = "twin-cool-emulator"
version = "0.1.0"
description = "オリジナルカードゲーム「最適解探索プログラム」のシミュレーションとWebUIアプリケーション"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.26.0",
    "streamlit>=1.28.0",
]
