[project]
name = "vrchat-twin-cool-emulator"
version = "0.1.0"
description = "VRChat「MedalGameWorld」ワールドのカードゲームシミュレーションとWebUIアプリケーション"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=1.26.0",
    "streamlit>=1.28.0",
]
